spring:
  datasource:
    url: jdbc:h2:file:./data/toss_payment_db;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# 결제 설정
toss:
  api-key: test_sk_P9BRQmyarY56W4lPgbnNrJ07KzLN
  execute-url: https://api.tosspayments.com/v1/payments/confirm
  cancel-url: https://api.tosspayments.com/v1/payments/{paymentKey}/cancel

inicis:
  mid: INIpayTest
  sign-key: SU5JTElURV9UUklQTEVERVNfS0VZRA==
  api-key: ItEQKi3rY7uvDS8l
  charset: UTF-8
  format: JSON