spring:
  profiles:
    active: local

# Local 환경 결제 설정 (테스트 환경)
toss:
  api-key: test_sk_P9BRQmyarY56W4lPgbnNrJ07KzLN
  execute-url: https://api.tosspayments.com/v1/payments/confirm
  cancel-url: https://api.tosspayments.com/v1/payments/{paymentKey}/cancel

inicis:
  mid: INIpayTest
  sign-key: SU5JTElURV9UUklQTEVERVNfS0VZRA==
  api-key: ItEQKi3rY7uvDS8l
  charset: UTF-8
  format: JSON

logging:
  level:
    com.example.payment: DEBUG
    root: INFO