spring:
  profiles:
    active: stg

# Staging 환경 결제 설정 (테스트 환경)
toss:
  api-key: test_ck_D5GePWvyJnrK0W0k6q8gLzN97Eoq
  execute-url: https://pay.toss.im/api/v2/execute

inicis:
  mid: INIpayTest
  sign-key: SU5JTElURV9UUklQTEVERVNfS0VZRA==
  api-key: ItEQKi3rY7uvDS8l
  charset: UTF-8
  format: JSON

logging:
  level:
    com.example.payment: WARN
    root: INFO